<a href="https://colab.research.google.com/github/jgomezfl/AlgorithmsUN2022II/blob/circleci-project-setup/Quiz6/Quiz6_jgomezfl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from decimal import DecimalException
import pandas as pd

dictionary = {'Combination': ['100 - 10','250 - 10','400 - 10','100 - 25','250 - 25','400 - 25','100 - 40','250 - 40','400 - 40'],
              'Sharpe Ratio': [-0.09927726278751382,-0.06383220938922404,-0.11556656870700378,-0.15532997271616197,-0.043408377127151385,-0.0397167175419396,-0.027510246640276605,-0.020259057683570014,0.027413036722729225]}
resultsDataframe = pd.DataFrame(dictionary)

resultsDataframe

  Combination  Sharpe Ratio
0    100 - 10     -0.099277
1    250 - 10     -0.063832
2    400 - 10     -0.115567
3    100 - 25     -0.155330
4    250 - 25     -0.043408
5    400 - 25     -0.039717
6    100 - 40     -0.027510
7    250 - 40     -0.020259
8    400 - 40      0.027413