<a href="https://colab.research.google.com/github/jgomezfl/AlgorithmsUN2022II/blob/circleci-project-setup/Quiz6/Quiz6_jgomezfl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
from decimal import DecimalException
import pandas as pd

dictionary = {'Combination': ['100 - 10','250 - 10','400 - 10','100 - 25','250 - 25','400 - 25','100 - 40','250 - 40','400 - 40'],
              'Sharpe Ratio': [-0.08927653324567636,-0.04897809208336071,-0.10306353039721501,-0.15044011017447423,-0.02962481650318019,-0.02689671921389419,-0.027492080644852965,-0.008676253891748925,0.039030037716718036]}
resultsDataframe = pd.DataFrame(dictionary)

resultsDataframe

  Combination  Sharpe Ratio
0    100 - 10     -0.089277
1    250 - 10     -0.048978
2    400 - 10     -0.103064
3    100 - 25     -0.150440
4    250 - 25     -0.029625
5    400 - 25     -0.026897
6    100 - 40     -0.027492
7    250 - 40     -0.008676
8    400 - 40      0.039030